{% set name = "stracking" %}
{% set version = "0.1.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/sylvainprigent/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 3095e06463a17256b87721da7315cd3a183cbf39818bb92b9b24cb4c10dc2d54

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - numpy
    - pip
    - python >=3.7
    - scipy
  run:
    - numpy
    - python >=3.7
    - scikit-image >=0.18.1
    - scipy >=1.6.3

test:
  imports:
    - stracking
    - stracking.containers
    - stracking.data
    - stracking.detectors
    - stracking.features
    - stracking.filters
    - stracking.io
    - stracking.linkers
    - stracking.observers
    - stracking.properties
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sylvainprigent/stracking
  summary: Particles tracking for scientific imaging
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
